# Generated by Django 3.1.7 on 2021-05-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluatorApp', '0003_auto_20210509_2252'),
        ('authApp', '0002_auto_20210418_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluatorApp.section'),
        ),
    ]
