# Generated by Django 3.1.7 on 2021-05-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_auto_20210509_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='subject_code',
        ),
    ]
