# Generated by Django 3.1.7 on 2021-05-09 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluatorApp', '0005_auto_20210510_0138'),
        ('authApp', '0004_remove_userdetails_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='subject_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluatorApp.subjectcode'),
        ),
    ]
