# Generated by Django 3.1.7 on 2021-05-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluatorApp', '0003_auto_20210509_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='sd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
