# Generated by Django 3.1.7 on 2021-05-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluatorApp', '0004_auto_20210510_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evaluatorApp.subjectcode'),
        ),
        migrations.AddField(
            model_name='test',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evaluatorApp.subjectcode'),
        ),
    ]
